# -*- coding: utf-8 -*-
"""youtube-api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167YwUuGrvjnwC7twqe91-MbLR98NgYkF
"""

import requests
import pandas as pd
import time

API_KEY = ""
#to get this key use the link
# https://www.youtube.com/watch?v=N18czV5tj5o

CHANNEL_ID = "UCmMGlb7mGXYVthrXYSwlQhw"
#https://www.youtube.com/channel/UCmMGlb7mGXYVthrXYSwlQhw
#https://www.youtube.com/channel/UCxmkk8bMSOF-UBF43z-pdGQ

pageToken = ""
url = "https://www.googleapis.com/youtube/v3/search?key="+API_KEY+"&channelId="+CHANNEL_ID+"&part=snippet,id&order=date&maxResults=1000"+pageToken

response=requests.get(url).json()

video_id = response['items'][0]['id']['videoId']

video_id

response['items'][0]

for video in response['items']:
  if video['id']['kind']=='youtube#video':
    video_id = video['id']['videoId']
    video_title = video['snippet']['title']
    upload_date = video['snippet']['publishedAt']
    upload_date = str(upload_date).split('T')[0]#makes sure that we are only left with the date and no timestamp


#print(video_id)
#print(video_title)
#print(upload_date)

"""##2nd API call"""

video_stats = "https://www.googleapis.com/youtube/v3/videos?id="+video_id+"&channelId="+CHANNEL_ID+"&part=statistics&key="+API_KEY
response_video_stats = requests.get(video_stats).json()

response_video_stats['items']

likes = response_video_stats['items'][0]['statistics']['likeCount']
dislike = response_video_stats['items'][0]['statistics']['commentCount']
views = response_video_stats['items'][0]['statistics']['viewCount']

"""#building a dataframe to store the results"""

df = pd.DataFrame(columns=["video_id","video_title","upload_date","likes","dislikes","views"])

for video in response['items']:
  if video['id']['kind']=='youtube#video':
    video_id = video['id']['videoId']
    video_title = video['snippet']['title']
    upload_date = video['snippet']['publishedAt']
    upload_date = str(upload_date).split('T')[0]#makes sure that we are only left with the date and no timestamp


    #second API CALL
    video_stats = "https://www.googleapis.com/youtube/v3/videos?id="+video_id+"&channelId="+CHANNEL_ID+"&part=statistics&key="+API_KEY
    response_video_stats = requests.get(video_stats).json()
    response_video_stats['items']

    likes = response_video_stats['items'][0]['statistics']['likeCount']
    dislike = response_video_stats['items'][0]['statistics']['commentCount']
    views = response_video_stats['items'][0]['statistics']['viewCount']

    #SAVE IN PANDAS
    df = df.append({'video_id':video_id,'video_title':video_title,'upload_date':upload_date,'likes':likes,'dislike':dislike,'views':views},ignore_index=True)

df.tail()

